apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  application.yml: |
    server:
      port: 8888
    spring:
      application:
        name: API-Gateway
      cloud:
        gateway:
          routes:
            - id: User-service
              uri: http://user-service:7070
              predicates:
                - Path=/user/**
              filters:
                - StripPrefix=1
            - id: Attendance-service
              uri: http://attendance-service:6060
              predicates:
                - Path=/attendance/**
              filters:
                - StripPrefix=1
            - id: Finance-service
              uri: http://finance-service:8080
              predicates:
                - Path=/finance/**
              filters:
                - StripPrefix=1
        discovery:
          enabled: false
    jwt:
      jwe:
        key: ${JWE_KEY}
      jws:
        key: ${JWS_KEY}
    logging:
      level:
        org.springframework.cloud.gateway: TRACE
        org.springframework.cloud.loadbalancer: TRACE
        org.springframework.web.reactive.function.client: TRACE
        reactor.netty.http.client: DEBUG
        org.springframework.cloud.gateway.filter.LoadBalancerClientFilter: TRACE
        org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: TRACE
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  selector:
    matchLabels:
      app: api-gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: parkjunhyeon/msa_api-gw:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
          env:
            - name: JWE_KEY
              valueFrom:
                secretKeyRef:
                  name: api-gateway-secret
                  key: JWE_KEY
            - name: JWS_KEY
              valueFrom:
                secretKeyRef:
                  name: api-gateway-secret
                  key: JWS_KEY
            - name: SPRING_CLOUD_CONFIG_ENABLED
              value: "false"
          volumeMounts:
            - mountPath: /app/config
              name: config-volume
      volumes:
        - name: config-volume
          configMap:
            name: api-gateway-config
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  selector:
    app: api-gateway
  type: NodePort
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 30080
