apiVersion: v1
kind: Secret
metadata:
  name: corebank-secret
type: Opaque
stringData:
  DB_PASSWORD: "1234"
  DB_URL: "jdbc:mysql://mysql:3306/banking"
  DB_USERNAME: "root"
  EMAIL_PASSWORD: "lfyywzrymhinrbug"
  EMAIL_USERNAME: "j525252p"
  JWE_KEY: "doif023nsdfoasdjfkosadfksajd"
  JWS_KEY: "dGhpc19pc19hX3ZlcnlfbG9uZ19hbmRfc2VjdXJlX2tleV9mb3JfaHMyNTZfYWxnb3JpdGhtX2F0X2xlYXN0XzMyX2J5dGVz"
